<?php
  $sectionSponsors = array (
    'key' => '56e02209621750',
    'name' => 'sponsors',
    'label' => 'Sponsors',
    'display' => 'block',
    'sub_fields' => array (
      array (
        'key' => 'field_5872671b517a8',
        'label' => 'Sponsor Row',
        'name' => 'sponsor_row',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => '',
        'max' => '',
        'layout' => 'table',
        'button_label' => 'Add Sponsor Row',
        'sub_fields' => array (
          array (
            'key' => 'field_5872672b517a9',
            'label' => 'Sponsor Type',
            'name' => 'sponsor_type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'choices' => array (
              'platinum' => 'Platinum',
              'gold' => 'Gold',
              'silver' => 'Silver',
              'bronze' => 'Bronze',
              'startup' => 'Startup',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'vertical',
            'return_format' => 'value',
          ),
          array (
            'key' => 'field_5872679d517ab',
            'label' => 'Sponsor',
            'name' => 'sponsor',
            'type' => 'relationship',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array (
              0 => 'sponsor',
            ),
            'taxonomy' => array (
            ),
            'filters' => array (
              0 => 'search',
              1 => 'post_type',
              2 => 'taxonomy',
            ),
            'elements' => '',
            'min' => '',
            'max' => '',
            'return_format' => 'object',
          ),
        ),
      ),
    ),
    'min' => '',
    'max' => '',
  );