<?php
  $sectionAgenda = array (
    'key' => '52g216po5erb2',
    'name' => 'agenda',
    'label' => 'Agenda',
    'display' => 'block',
    'sub_fields' => array (
      array (
        'key' => 'field_58c597a05d3e8',
        'label' => 'Days',
        'name' => 'days',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 2,
        'max' => 2,
        'layout' => 'block',
        'button_label' => 'Add Day',
        'sub_fields' => array (
          array (
            'key' => 'field_58c59b4541331',
            'label' => 'Schedule',
            'name' => 'schedule',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => '',
            'min' => '',
            'max' => '',
            'layout' => 'table',
            'button_label' => 'Aggiungi Riga',
            'sub_fields' => array (
              array (
                'key' => 'field_58c59c2241332',
                'label' => 'Type',
                'name' => 'type',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array (
                  'talk' => 'Talk',
                  'other' => 'Other',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'save_other_choice' => 0,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
              ),
              array (
                'key' => 'field_58c59c4241333',
                'label' => 'Talk',
                'name' => 'talk',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                  array (
                    array (
                      'field' => 'field_58c59c2241332',
                      'operator' => '==',
                      'value' => 'talk',
                    ),
                  ),
                ),
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => 1,
                'max' => 1,
                'layout' => 'row',
                'button_label' => 'Aggiungi Riga',
                'sub_fields' => array (
                  array (
                    'key' => 'field_58c59c8941335',
                    'label' => 'Hour',
                    'name' => 'hour',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array (
                    'key' => 'field_58c59c9341336',
                    'label' => 'Speaker',
                    'name' => 'speaker',
                    'type' => 'relationship',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'post_type' => array (
                      0 => 'speaker',
                    ),
                    'taxonomy' => array (
                    ),
                    'filters' => array (
                      0 => 'search',
                      1 => 'post_type',
                      2 => 'taxonomy',
                    ),
                    'elements' => '',
                    'min' => 0,
                    'max' => 1,
                    'return_format' => 'object',
                  ),
                ),
              ),
              array (
                'key' => 'field_58c59c5541334',
                'label' => 'Other',
                'name' => 'other',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array (
                  array (
                    array (
                      'field' => 'field_58c59c2241332',
                      'operator' => '==',
                      'value' => 'other',
                    ),
                  ),
                ),
                'wrapper' => array (
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'collapsed' => '',
                'min' => 1,
                'max' => 1,
                'layout' => 'table',
                'button_label' => 'Aggiungi Riga',
                'sub_fields' => array (
                  array (
                    'key' => 'field_58c59ca641337',
                    'label' => 'Hour',
                    'name' => 'hour',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array (
                    'key' => 'field_58c59cab41338',
                    'label' => 'Text',
                    'name' => 'text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array (
                    'key' => 'field_58c5o94241332',
                    'label' => 'Color Type',
                    'name' => 'color_type',
                    'type' => 'radio',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array (
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array (
                      'red' => 'Red',
                      'grey' => 'Grey',
                    ),
                    'allow_null' => 0,
                    'other_choice' => 0,
                    'save_other_choice' => 0,
                    'default_value' => '',
                    'layout' => 'vertical',
                    'return_format' => 'value',
                  ),
                ),
              ),
            ),
          ),
        ),
      ),

    ),
    'min' => '',
    'max' => '',
  );