<?php
  $sectionInfo = array (
    'key' => '56e0350e1032c',
    'name' => 'info',
    'label' => 'Info',
    'display' => 'block',
    'sub_fields' => array (
      array (
        'key' => 'field_56e022u667c65',
        'label' => 'Suptitle',
        'name' => 'suptitle',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_56e02259a7c65',
        'label' => 'Title',
        'name' => 'title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_56e04336999b5',
        'label' => 'Content',
        'name' => 'content',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
      ),
      array (
        'key' => 'field_5730aappw3114',
        'label' => 'Position',
        'name' => 'position',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array (
          'after-hero' => 'After Hero',
          'normal' => 'Normal',
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 'light',
        'layout' => 'horizontal',
      ),
      array (
        'key' => 'field_57308352w3114',
        'label' => 'Type',
        'name' => 'type',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array (
          'left_text' => 'Left Text',
          'right_text' => 'Right Text',
          'left_image' => 'Left Image',
          'right_image' => 'Right Image',
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 'light',
        'layout' => 'horizontal',
      ),
      array (
        'key' => 'field_56e039c46d564',
        'label' => 'Image',
        'name' => 'image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array (
        'key' => 'field_56e022u099c65',
        'label' => 'Animation ID',
        'name' => 'animationid',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
    ),
    'min' => '',
    'max' => '',
  );