<?php
  $sectionSpeaker = array (
    'key' => '56e035oooa35c',
    'name' => 'speaker',
    'label' => 'Speaker',
    'display' => 'block',
    'sub_fields' => array (
      array (
        'key' => 'field_540t37a433039',
        'label' => 'Speaker',
        'name' => 'speaker_list',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array (
          0 => 'speaker',
        ),
        'taxonomy' => array (
        ),
        'filters' => array (
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => '',
        'return_format' => 'object',
      ),
      array (
        'key' => 'field_56e03ee56d564',
        'label' => 'Featured Image',
        'name' => 'featured_image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array (
        'key' => 'field_58587llk8d509',
        'label' => 'Position',
        'name' => 'position',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array (
          'left' => 'Left',
          'right' => 'Right',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => '',
        'layout' => 'horizontal',
        'return_format' => 'value',
      ),
      array (
        'key' => 'field_00987llk8d509',
        'label' => 'Padding Bottom',
        'name' => 'padding_bottom',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array (
          'padding_bottom' => 'Yes',
          'no_padding' => 'No',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => '',
        'layout' => 'horizontal',
        'return_format' => 'value',
      ),
    ),
    'min' => '',
    'max' => '',
  );