<?php
  $sectionHero = array (
    'key' => '56e0350e1a35c',
    'name' => 'hero',
    'label' => 'Hero',
    'display' => 'block',
    'sub_fields' => array (
      array (
        'key' => 'field_56e03559a7c65',
        'label' => 'Suptitle',
        'name' => 'suptitle',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_5873b934879cc',
        'label' => 'Title',
        'name' => 'title',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 1,
      ),
      array (
        'key' => 'field_56e02906999b5',
        'label' => 'Small Text',
        'name' => 'small_text',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
      ),
      array (
        'key' => 'field_5730aac2a3114',
        'label' => 'Type',
        'name' => 'type',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array (
          'no-image' => 'No Image',
          'image-right' => 'Image Right',
          'image-full' => 'Image Full',
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 'light',
        'layout' => 'horizontal',
      ),
      array (
        'key' => 'field_56f727bfa7c67',
        'label' => 'Hero Image',
        'name' => 'hero_image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array (
          array (
            array (
              'field' => 'field_5730aac2a3114',
              'operator' => '==',
              'value' => 'image-right',
            ),
          ),
          array (
            array (
              'field' => 'field_5730aac2a3114',
              'operator' => '==',
              'value' => 'image-full',
            ),
          ),
        ),
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
    ),
    'min' => '',
    'max' => '',
  );