<?php
  $sectionInfo = array (
    'key' => '56e0350e1032c',
    'name' => 'info',
    'label' => 'Info',
    'display' => 'block',
    'sub_fields' => array (
      array (
        'key' => 'field_56e02259a7c65',
        'label' => 'Title',
        'name' => 'title',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array (
        'key' => 'field_56e04336999b5',
        'label' => 'Content',
        'name' => 'content',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
      ),
      array (
        'key' => 'field_5730aappw3114',
        'label' => 'Type',
        'name' => 'type',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array (
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array (
          'after-hero' => 'After Hero',
          'normal' => 'Normal',
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 'light',
        'layout' => 'horizontal',
      ),
    ),
    'min' => '',
    'max' => '',
  );